name: Nexus Script Runner

on:
  schedule:
    # Run once a day at midnight (adjust timing as needed)
    - cron: "0 0 * * *"

  workflow_dispatch: # Allows manual triggering.

jobs:
  run-nexus:
    runs-on: ubuntu-latest

    steps:
    - name: Update and Install curl
      run: |
        sudo apt update
        sudo apt install -y curl

    - name: Fetch and Run Nexus Script
      run: |
        if [ -f "nexus.sh" ]; then
          rm nexus.sh
        fi
        curl -sSL https://raw.githubusercontent.com/zunxbt/nexus-prover/main/nexus.sh | bash
